// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowerPressSettingsManager.Data;

#nullable disable

namespace PowerPressSettingsManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("PowerPressSettingsManager.Moduls.CoilSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeedLenght")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LeftHight")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialGrade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PressSettingId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProgressionOrTransfer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecommendedSpeedFeeder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RightHight")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RunSide")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PressSettingId")
                        .IsUnique();

                    b.ToTable("CoulSettings");
                });

            modelBuilder.Entity("PowerPressSettingsManager.Moduls.PressSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("ClampingHight")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LastTimeRun")
                        .HasColumnType("TEXT");

                    b.Property<int>("MagnetBeltSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecommendedRunningSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<float>("RunningHight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("PressSettings");
                });

            modelBuilder.Entity("PowerPressSettingsManager.Moduls.CoilSetting", b =>
                {
                    b.HasOne("PowerPressSettingsManager.Moduls.PressSetting", "PressSetting")
                        .WithOne("CoilSetting")
                        .HasForeignKey("PowerPressSettingsManager.Moduls.CoilSetting", "PressSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PressSetting");
                });

            modelBuilder.Entity("PowerPressSettingsManager.Moduls.PressSetting", b =>
                {
                    b.Navigation("CoilSetting")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
